from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.colors import HexColor

OUT = r'C:\Users\91730\Downloads\affiliate-ae-whatsapp-ordering-update\AE_Backend_Purchase_Redeem_Flow.pdf'
W,H=A4; navy=HexColor('#10243b'); purple=HexColor('#5546d9'); muted=HexColor('#5e6b7b'); light=HexColor('#f3f6fb')
s=getSampleStyleSheet()
s.add(ParagraphStyle(name='TA',parent=s['Title'],fontName='Helvetica-Bold',fontSize=24,leading=29,textColor=navy,alignment=TA_CENTER,spaceAfter=8))
s.add(ParagraphStyle(name='SA',parent=s['Normal'],fontSize=11,leading=16,textColor=muted,alignment=TA_CENTER,spaceAfter=18))
s.add(ParagraphStyle(name='HA',parent=s['Heading1'],fontName='Helvetica-Bold',fontSize=16,leading=20,textColor=purple,spaceBefore=14,spaceAfter=7))
s.add(ParagraphStyle(name='BA',parent=s['BodyText'],fontSize=9.5,leading=14,textColor=navy,spaceAfter=6))
s.add(ParagraphStyle(name='CA',parent=s['BodyText'],fontSize=9.5,leading=14,textColor=navy,backColor=light,borderColor=HexColor('#d8e1ef'),borderWidth=.5,borderPadding=8,spaceBefore=5,spaceAfter=8))
P=lambda x,st='BA': Paragraph(x,s[st])
def bullets(xs): return [P('&bull; '+x) for x in xs]
def table(rows,widths):
    t=Table(rows,colWidths=widths); t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),light),('GRID',(0,0),(-1,-1),.35,HexColor('#d8e1ef')),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),7),('RIGHTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)])); return t
story=[Spacer(1,20*mm),P('Affiliate AE','TA'),P('Backend Purchase, Points & Redemption Flow','SA'),P('Client-facing technical overview of the current system behavior. The UI can change independently; the business rules and Supabase operations remain on the backend.','CA'),P('1. System overview','HA'),P('Affiliate AE connects customers and merchants through a customer QR code. A merchant scans the customer QR, the backend verifies the customer, and the merchant completes either a purchase transaction that issues points or a redemption transaction that applies a discount.')]
story.append(table([[P('<b>Actor</b>'),P('<b>Responsibility</b>')],[P('Customer'),P('Shows the personal QR code and receives points, balance updates and notifications.')],[P('Merchant'),P('Scans the QR, verifies the customer and chooses purchase/earn or redeem/discount.')],[P('Backend API'),P('Validates identity, applies reward rules, writes transactions and queues notifications.')],[P('Supabase'),P('Stores customers, balances, orders, redemptions, settings and notification logs.')]], [42*mm,128*mm]))
story += [P('2. Customer QR identification','HA')]+bullets(['The customer app creates a QR payload containing the customer code (or customer UUID for compatibility).','The merchant scanner accepts both the current JSON payload and legacy plain identifiers.','The backend resolves the identifier against the customers table by customer_code or UUID.','After verification, the response includes customer name, phone, code, balance and whether the customer is new to that merchant.','If the identifier cannot be matched, the API returns “Customer not found”; this is an identity lookup issue, not a points calculation issue.'])
story += [P('3. Purchase and earn-points flow','HA'),P('This is the normal purchase path used when a customer buys from a merchant.')]
story.append(table([[P('<b>Step</b>'),P('<b>Backend action</b>')],[P('1. Scan'),P('Merchant scans the customer QR and submits the customer code.')],[P('2. Enter amount'),P('Merchant enters a purchase amount. Current minimum: INR 100.')],[P('3. Select earn rate'),P('Merchant selects the configured points per INR 100 option. Merchant caps/settings are applied.')],[P('4. Create purchase'),P('POST /api/checkouts processes the purchase and writes the order and reward transaction with idempotency protection.')],[P('5. Update balances'),P('Customer and merchant-specific reward balances are updated by the database transaction.')],[P('6. Notify'),P('Push notifications are sent to customer and merchant. WhatsApp is queued/sent when configured.')],[P('7. Refresh UI'),P('Dashboard, orders and balances are refreshed so new values appear.')]], [33*mm,137*mm]))
story += [P('4. Redeem-points-for-discount flow','HA'),P('This flow consumes points already available at the merchant and calculates a discount from the transaction amount.')]+bullets(['Merchant selects "Redeem points for discount".','Merchant enters transaction amount and points to redeem. Current validation: amount minimum INR 100, points minimum 100 and maximum 1,000.','Backend verifies the customer and checks the merchant-specific balance.','Discount percentage = (points redeemed / 100) x merchant discount rate per 100 points.','Discount amount = transaction amount x discount percentage / 100.','A point_redemptions record is created, then global and merchant-specific balances are deducted.','Customer receives the redemption result and an optional WhatsApp redemption message.'])
story += [P('5. Reward settings and dynamic rules','HA')]+bullets(['Admin settings define earn-rate options, redeem options, subscription settings and system defaults.','Merchant settings can override earn points per ₹100 and redeem discount per 100 points.','The UI reads these values from the backend, so settings changes do not require redesigning screens.','Backend calculations are authoritative; the client UI only collects input and displays the result.'])
story += [P('6. Notifications','HA')]+bullets(['Purchase event: customer and merchant push notifications are triggered after a successful purchase.','Redemption event: customer receives the redemption result; WhatsApp can use the configured redemption template.','Registration event: welcome/QR and temporary-password WhatsApp templates are used when configured.','WhatsApp failures are logged separately and should not undo a successfully committed purchase or redemption.'])
story += [P('7. Current implementation note','HA'),P('The current backend exposes purchase/earn and redemption as two separate, validated operations. The UI can offer both choices after scanning. A single atomic transaction that simultaneously redeems points and issues new purchase points would require an additional backend endpoint/database function; it should not be assumed from the current separate endpoints.','CA')]
story += [P('8. Client testing checklist','HA')]+bullets(['Scan a valid customer QR and confirm customer name/code/balance appears.','Complete an INR 100+ purchase with a selected earn rate; verify order, balance and notification.','Redeem 100-1,000 points with sufficient balance; verify discount, deduction and history.','Try invalid customer code, insufficient balance, amount below INR 100 and points outside limits.','Repeat a request with the same idempotency key and confirm it does not create a duplicate purchase.','Verify WhatsApp and push delivery independently; notification failure should remain visible in logs.'])+[P('Summary','HA'),P('The backend logic is the stable foundation: scan and verify, validate rules, write the transaction, update balances, and notify. The UI can be redesigned to make this flow clearer without changing the underlying accounting logic.')]
def footer(c,d):
    c.saveState(); c.setStrokeColor(HexColor('#d8e1ef')); c.line(18*mm,14*mm,W-18*mm,14*mm); c.setFont('Helvetica',7.5); c.setFillColor(muted); c.drawString(18*mm,9*mm,'Affiliate AE - Backend Purchase & Rewards Flow'); c.drawRightString(W-18*mm,9*mm,'Page %d'%d.page); c.restoreState()
SimpleDocTemplate(OUT,pagesize=A4,rightMargin=18*mm,leftMargin=18*mm,topMargin=16*mm,bottomMargin=20*mm).build(story,onFirstPage=footer,onLaterPages=footer)
print(OUT)
