import { useDeferredValue, useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { ChevronRight, Plus, Search, Store } from 'lucide-react';
import { apiFetch, queryString } from '../api';
import { LoadingState, ErrorState, PaginationBar, PageHeader } from '../components/Common';
import { formatDateTime, formatCurrency, formatPoints, initials } from '../utils';
import type { Pagination } from '../types';
import { uiText } from '../uiText';
import '../admin-directory.css';
type Row=Record<string,any>;
function sourceLabel(source:unknown){return source==='self'?'Self registration':source==='merchant'?'Merchant onboarding':'Source not recorded';}
function Source({source}:{source:unknown}){return <span className={`admin-source-badge ${source==='self'?'self':source==='merchant'?'merchant':'unknown'}`}>{uiText(sourceLabel(source))}</span>;}

export function AdminCustomers(){
 const [page,setPage]=useState(1),[search,setSearch]=useState(''),[source,setSource]=useState('all');
 const deferredSearch=useDeferredValue(search.trim());
 useEffect(()=>setPage(1),[deferredSearch,source]);
 const q=useQuery({queryKey:['admin-customer-directory',page,deferredSearch,source],queryFn:({signal})=>apiFetch<{records:Row[];pagination:Pagination}>(`/api/admin/customers?${queryString({page,pageSize:25,search:deferredSearch,source})}`,{signal})});
 return <div className="admin-directory-page"><PageHeader title={uiText('Customers')} subtitle={uiText('Profiles and onboarding across your network')} actions={<Link className="button primary" to="/add-customer"><Plus size={16}/>{uiText('Add customer')}</Link>}/>
 <div className="admin-directory-metrics admin-customer-metrics"><article><span>{uiText('Matching customers')}</span><strong>{q.isPending?'…':q.isError?'—':q.data.pagination.total.toLocaleString('en-IN')}</strong></article><article><span>{uiText('Showing on this page')}</span><strong>{q.isPending?'…':q.isError?'—':q.data.records.length}</strong></article></div>
 <div className="list-toolbar admin-customer-toolbar"><label className="search-field"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={uiText('Search customers')} aria-label={uiText('Search customers')}/></label><label className="admin-source-filter"><span>{uiText('Onboarding source')}</span><select value={source} onChange={e=>setSource(e.target.value)}>{[['all','All onboarding sources'],['self','Self registration'],['merchant','Merchant onboarding'],['unknown','Source not recorded']].map(([key,label])=><option value={key} key={key}>{uiText(label)}</option>)}</select></label></div>
 {q.isPending?<LoadingState/>:q.isError?<ErrorState error={q.error} retry={()=>void q.refetch()}/>:<section className="table-panel"><div className="table-scroll"><table><thead><tr>{['Customer','Contact','Onboarding source','Registered','View'].map(label=><th key={label}>{uiText(label)}</th>)}</tr></thead><tbody>{q.data.records.map(c=><tr key={c.id}><td><Link className="admin-merchant-name" to={`/customers/${c.id}`}><span className="admin-directory-avatar">{initials(c.name || '')}</span><span><strong>{c.name}</strong><small>{c.customer_code}</small></span></Link></td><td><span className="admin-contact-stack"><span>{c.phone}</span><small>{c.email || '—'}</small></span></td><td><Source source={c.registration_source}/></td><td>{formatDateTime(c.created_at)}</td><td><Link className="icon-button" to={`/customers/${c.id}`} aria-label={`${uiText('View customer')} ${c.name}`}><ChevronRight size={18}/></Link></td></tr>)}</tbody></table></div>{!q.data.records.length&&<p className="admin-empty-message">{uiText('No records.')}</p>}<PaginationBar pagination={q.data.pagination} onPage={setPage}/></section>}</div>;
}

const tabs=[['orders','Purchases'],['redemptions','Redemptions'],['payments','Payment records']] as const;
const columns:Record<string,string[]>={orders:['order_no','amount','reward_points','source'],redemptions:['transaction_amount','points_redeemed','discount_amount'],payments:['amount','status']};
const labels:Record<string,string>={order_no:'Order number',amount:'Bill amount',reward_points:'Points issued',source:'Source',transaction_amount:'Bill amount',points_redeemed:'Points redeemed',discount_amount:'Discount',status:'Status'};
function amountCell(key:string,value:unknown){return value==null?'—':['amount','transaction_amount','discount_amount'].includes(key)?formatCurrency(Number(value)):String(value);}
export function AdminCustomerDetails(){
 const {id=''}=useParams();const [type,setType]=useState('orders'),[page,setPage]=useState(1);
 useEffect(()=>{setPage(1);setType('orders');},[id]);
 const q=useQuery({queryKey:['admin-customer-detail',id],queryFn:({signal})=>apiFetch<{customer:Row;memberships:Row[];onboardingMerchant:Row|null}>(`/api/admin/customers/${encodeURIComponent(id)}/details`,{signal})});
 const a=useQuery({queryKey:['admin-customer-activity',id,type,page],queryFn:({signal})=>apiFetch<{records:Row[];pagination:Pagination}>(`/api/admin/customers/${encodeURIComponent(id)}/activity?${queryString({type,page,pageSize:25})}`,{signal})});
 if(q.isPending)return <LoadingState/>;if(q.isError)return <ErrorState error={q.error} retry={()=>void q.refetch()}/>;
 const {customer:c,memberships,onboardingMerchant:m}=q.data;
 return <div className="admin-directory-page"><Link className="button secondary" to="/customers">{uiText('Back to customers')}</Link><header className="admin-detail-heading"><span className="admin-directory-avatar">{initials(c.name || '')}</span><div><h1>{c.name}</h1><p>{c.customer_code}</p></div></header>
 <section className="panel"><h2>{uiText('Onboarding details')}</h2><dl className="admin-customer-profile-grid"><div><dt>{uiText('Phone number')}</dt><dd>{c.phone || '—'}</dd></div><div><dt>{uiText('Email')}</dt><dd>{c.email || '—'}</dd></div><div><dt>{uiText('Registered')}</dt><dd>{formatDateTime(c.created_at)}</dd></div><div><dt>{uiText('Onboarding source')}</dt><dd><Source source={c.registration_source}/></dd></div><div><dt>{uiText('Original onboarding merchant')}</dt><dd>{m?<Link to={`/merchants/${m.id}`}>{m.name} · {m.merchant_code}</Link>:uiText(c.registration_source==='self'?'Not applicable':'Source not recorded')}</dd></div></dl><p className="admin-directory-note">{uiText('Source describes the recorded registration path. The individual who performed onboarding may not have been recorded.')}</p></section>
 <section className="panel"><div className="panel-heading"><h2>{uiText('Linked merchants')}</h2><span className="admin-source-badge">{memberships.length}</span></div><div className="admin-linked-shops">{memberships.map(row=><Link key={row.merchant_id} to={`/merchants/${row.merchant_id}`}><span className="admin-directory-avatar"><Store size={20}/></span><span><strong>{row.merchants?.name || row.merchant_id}</strong><small>{formatPoints(Number(row.reward_points || 0))} {uiText('Points')}</small><small>{uiText('Joined')}: {formatDateTime(row.joined_at)}</small></span><ChevronRight size={18}/></Link>)}</div>{!memberships.length&&<p>{uiText('No linked merchants.')}</p>}</section>
 <nav className="admin-detail-tabs" aria-label={uiText('Customer activity sections')}>{tabs.map(([key,label])=><button aria-pressed={type===key} key={key} onClick={()=>{setType(key);setPage(1)}}>{uiText(label)}</button>)}</nav>
 <section className="panel"><div className="panel-heading"><h2>{uiText(tabs.find(([key])=>key===type)![1])}</h2>{a.data&&<span className="admin-source-badge">{a.data.pagination.total} {uiText('records')}</span>}</div><p className="admin-directory-note">{uiText('Recorded activity across all linked merchants')}</p>{a.isPending?<LoadingState/>:a.isError?<ErrorState error={a.error} retry={()=>void a.refetch()}/>:<><div className="table-scroll"><table><thead><tr><th>{uiText('Merchant')}</th><th>{uiText('Date')}</th>{columns[type].map(key=><th key={key}>{uiText(labels[key])}</th>)}</tr></thead><tbody>{a.data.records.map(row=><tr key={row.id}><td><Link to={`/merchants/${row.merchant_id}`}>{row.merchants?.name || row.merchant_id}</Link><small className="table-note">{row.merchants?.merchant_code}</small></td><td>{formatDateTime(row.created_at)}</td>{columns[type].map(key=><td key={key}>{amountCell(key,row[key])}</td>)}</tr>)}</tbody></table></div>{!a.data.records.length&&<p>{uiText('No records.')}</p>}<PaginationBar pagination={a.data.pagination} onPage={setPage}/></>}</section></div>;
}
