import { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CheckCircle2, MapPin, LogOut, Save, XCircle } from 'lucide-react';
import { apiFetch } from '../api';
import type { UserProfile } from '../types';
import { PageHeader, LoadingState, ErrorState } from '../components/Common';

type Merchant = { id: string; name: string; merchant_code: string; phone?: string; address?: string; latitude?: number; longitude?: number; active?: boolean; merchant_categories?: { name?: string } };
type Visit = { id: string; merchant_id: string; status: string; check_in_at: string; check_out_at?: string; distance_m?: number; accuracy_m?: number; merchants?: { name?: string; merchant_code?: string } };
const distance = (a: number, b: number, c: number, d: number) => { const r = (n: number) => n * Math.PI / 180; const x = Math.sin(r(c - a) / 2) ** 2 + Math.cos(r(a)) * Math.cos(r(c)) * Math.sin(r(d - b) / 2) ** 2; return 6371000 * 2 * Math.atan2(Math.sqrt(x), Math.sqrt(1 - x)); };

export function FieldManager({ user, onLogout }: { user: UserProfile; onLogout: () => void }) {
  const qc = useQueryClient(); const [position, setPosition] = useState<GeolocationPosition | null>(null); const [selected, setSelected] = useState<Merchant | null>(null); const [visit, setVisit] = useState<Visit | null>(null); const [notes, setNotes] = useState(''); const [message, setMessage] = useState('');
  const merchants = useQuery({ queryKey: ['field-merchants'], queryFn: () => apiFetch<{ merchants: Merchant[] }>('/api/field/merchants') });
  const visits = useQuery({ queryKey: ['field-visits'], queryFn: () => apiFetch<{ visits: Visit[] }>('/api/field/visits') });
  const nearby = useMemo(() => merchants.data?.merchants.map(m => ({ ...m, distance: position && m.latitude && m.longitude ? distance(position.coords.latitude, position.coords.longitude, Number(m.latitude), Number(m.longitude)) : null })).sort((a, b) => (a.distance ?? Infinity) - (b.distance ?? Infinity)) || [], [merchants.data, position]);
  useEffect(() => { if (!navigator.geolocation) return; const id = navigator.geolocation.watchPosition(setPosition, () => setMessage('Location permission is required to calculate distance and check in.'), { enableHighAccuracy: true, maximumAge: 15000, timeout: 15000 }); return () => navigator.geolocation.clearWatch(id); }, []);
  useEffect(() => { const active = visits.data?.visits.find(v => v.status === 'active'); if (active) setVisit(active); }, [visits.data]);
  const checkIn = useMutation({ mutationFn: async (merchant: Merchant) => { const p = await new Promise<GeolocationPosition>((resolve, reject) => navigator.geolocation.getCurrentPosition(resolve, reject, { enableHighAccuracy: true, timeout: 15000 })); return apiFetch<{ visit: Visit }>(`/api/field/visits/check-in`, { method: 'POST', body: JSON.stringify({ merchantId: merchant.id, latitude: p.coords.latitude, longitude: p.coords.longitude, accuracy: p.coords.accuracy }) }); }, onSuccess: (data) => { setVisit(data.visit); setMessage('Checked in successfully.'); void qc.invalidateQueries({ queryKey: ['field-visits'] }); }, onError: e => setMessage(e.message) });
  const checkOut = useMutation({ mutationFn: async () => { const p = await new Promise<GeolocationPosition>((resolve, reject) => navigator.geolocation.getCurrentPosition(resolve, reject, { enableHighAccuracy: true, timeout: 15000 })); return apiFetch<{ visit: Visit }>(`/api/field/visits/${visit?.id}/check-out`, { method: 'POST', body: JSON.stringify({ latitude: p.coords.latitude, longitude: p.coords.longitude, notes }) }); }, onSuccess: () => { setVisit(null); setNotes(''); setMessage('Visit completed.'); void qc.invalidateQueries({ queryKey: ['field-visits'] }); }, onError: e => setMessage(e.message) });
  const update = useMutation({ mutationFn: (payload: Record<string, unknown>) => apiFetch(`/api/field/visits/${visit?.id}/update`, { method: 'POST', body: JSON.stringify(payload) }), onSuccess: () => setMessage('Merchant update submitted for Admin approval.'), onError: e => setMessage(e.message) });
  const signOut = async () => { try { await apiFetch('/api/field/sessions/end', { method: 'POST' }); } finally { onLogout(); } };
  if (merchants.isPending) return <LoadingState />; if (merchants.isError) return <ErrorState error={merchants.error} retry={() => merchants.refetch()} />;
  return <div className="dashboard-page"><PageHeader title="Field Manager" subtitle={`Signed in as ${user.full_name || user.email}`} actions={<button className="button secondary" onClick={() => void signOut()}><LogOut size={16} />Sign out</button>} />
    {message ? <div className="state-panel" role="status">{message}</div> : null}
    {visit ? <section className="panel" style={{ borderColor: '#0f8a54' }}><h2>Active visit: {visit.merchants?.name || selected?.name || 'Merchant'}</h2><p>Checked in at {new Date(visit.check_in_at).toLocaleString()} · GPS accuracy {Math.round(visit.accuracy_m || 0)}m</p><div className="form-grid"><label>Visit notes<textarea value={notes} onChange={e => setNotes(e.target.value)} /></label></div><div style={{ display: 'flex', gap: 12, marginTop: 12 }}><button className="button primary" onClick={() => checkOut.mutate()} disabled={checkOut.isPending}><CheckCircle2 size={16} />{checkOut.isPending ? 'Checking out…' : 'Check out'}</button><button className="button secondary" onClick={() => update.mutate({ notes })} disabled={update.isPending}><Save size={16} />Submit merchant update</button></div></section> : null}
    <section className="panel"><div className="panel-heading"><div><h2>Nearby merchants</h2><p>Allow browser location to calculate distance. Check-in is allowed within 150m.</p></div><MapPin /></div><div className="table-scroll"><table><thead><tr><th>Merchant</th><th>Address</th><th>Distance</th><th>Action</th></tr></thead><tbody>{nearby.map(m => <tr key={m.id}><td><strong>{m.name}</strong><small>{m.merchant_code}</small></td><td>{m.address || 'No address saved'}</td><td>{m.distance == null ? 'Location unavailable' : `${Math.round(m.distance)} m`}</td><td><button className="button primary" disabled={Boolean(visit) || checkIn.isPending || m.distance == null} onClick={() => { setSelected(m); checkIn.mutate(m); }}><MapPin size={15} />Check in</button></td></tr>)}</tbody></table></div></section>
    <section className="panel"><div className="panel-heading"><div><h2>Recent visits</h2><p>Your completed field activity.</p></div><XCircle /></div><div className="table-scroll"><table><thead><tr><th>Merchant</th><th>Status</th><th>Check-in</th><th>Distance</th></tr></thead><tbody>{visits.data?.visits.map(v => <tr key={v.id}><td>{v.merchants?.name || v.merchant_id}</td><td><span className={`tag ${v.status === 'completed' ? 'success' : 'info'}`}>{v.status}</span></td><td>{new Date(v.check_in_at).toLocaleString()}</td><td>{v.distance_m ? `${Math.round(v.distance_m)}m` : '—'}</td></tr>)}</tbody></table></div></section>
  </div>;
}
