import { Link, useSearchParams } from 'react-router-dom';
import './legal.css';

const common = [
  ['About AE and the pilot', 'AE is operated by Affiliate Innovations, Chittur, Palakkad, Kerala, India – 678101. Customer and merchant participation is free during the current pilot. No subscription refund policy applies to this free pilot. Any future fees and applicable policies will be communicated before they take effect; these terms do not authorise undisclosed charges.'],
  ['Accounts and acceptable use', 'Provide accurate information, keep credentials private and report suspected unauthorised use promptly. Do not create false transactions, manipulate points, impersonate others, misuse personal data or interfere with the service. Account access may be restricted to investigate misuse or protect users, with an explanation where lawful and practicable.'],
  ['Purchases and payments', 'Customers pay merchants directly. Merchants are responsible for their goods, services, pricing, receipts and applicable purchase-related obligations. AE supports account and rewards administration; it does not promise the quality or availability of merchant products. These terms do not remove statutory consumer remedies or prevent contacting AE about a platform error.'],
  ['Changes, availability and disputes', 'Pilot features may change or be interrupted. Material changes to terms or future pricing will be communicated before taking effect. Report account or transaction errors to support with the merchant, date and transaction reference, but never send passwords. Applicable Indian law governs, without excluding mandatory consumer rights, employment rights or lawful forums. Nothing here excludes liability that cannot lawfully be excluded.'],
];
const customer = [
  ['Customer rewards', 'Reward issuance depends on a genuine eligible purchase and merchant confirmation. The current scan checkout requires a purchase of at least ₹100. Points are calculated from completed ₹100 units at the displayed merchant earning rate, capped at 100 points per purchase. Other transaction paths may differ; check the displayed transaction details before confirmation.'],
  ['Redemption and QR codes', 'The current Redeem + Issue checkout deducts a fixed 100 points when the merchant confirms the transaction and requires sufficient eligible points. The discount may be a flat rupee amount or a percentage, as displayed by the merchant. 100 points do not guarantee a fixed ₹100 discount. Showing a QR alone does not deduct points. My QR defaults to Issue Only; Redeem QR defaults to Redeem + Issue for the same customer. Protect your QR and check the transaction outcome.'],
  ['Expiry and corrections', 'The customer UI describes points as expiring one year from issue. The applicable expiry and eligible balance should be checked in the transaction/account record. Points are promotional rewards, not a deposit or an automatic right to cash withdrawal. Report missing, duplicated or incorrect points to support; corrections should follow verification, not invented purchase values. A purchase dispute must be raised with the merchant, without limiting statutory rights.'],
];
const merchant = [
  ['Merchant responsibilities', 'Keep store, contact, category and location details accurate. Issue and redeem rewards only for verified transactions with the correct customer. Clearly communicate the purchase amount, earning rate, discount and final payable amount before confirming. Do not describe rewards as guaranteed cash returns.'],
  ['Direct settlement and pilot fees', 'Customer purchase payments are made directly to the merchant. The merchant remains responsible for payment reconciliation, taxes, invoices and purchase complaints as applicable. AE merchant participation is free during the pilot. Post-pilot pricing is undecided; no future price is promised by this draft.'],
  ['Customer data and credentials', 'Use customer details only for authorised service and transaction purposes. Do not copy customer information for unrelated marketing, share passwords or expose QR identifiers. Verify merchant onboarding credentials and change a temporary password when required. Report suspicious activity to AE.'],
];
const field = [
  ['Employee use', 'Field managers are employees of Affiliate Innovations. These portal terms govern authorised system use; they do not replace an employment agreement or determine salary, hours, leave, disciplinary procedures or termination rights. Employment matters remain subject to applicable law and approved company policies.'],
  ['Merchant onboarding and visits', 'Obtain accurate merchant information and permission before uploading store photographs or sharing credentials. Review business details and coordinates before submission. Record actual visits, use your own assigned login and keep merchant/customer information confidential. Submitted merchant updates require Admin review.'],
  ['Location and activity notice', 'The portal records login/logout sessions and visit check-in/out timestamps, GPS coordinates, accuracy, distance and notes for field operations and supervision. The current implementation also requests browser location while the Field Manager page is open to calculate nearby merchants; it is not native background tracking. Location may be unavailable or inaccurate. GPS is not conclusive evidence of misconduct. Employees may contact support about incorrect records or privacy concerns.'],
  ['Company policy limitations', 'KYC document requirements, territory assignment, escalation rules and other employment policies must be supplied and approved separately. Do not treat placeholder guidance in the portal as an approved employment or compliance policy.'],
];
const privacy = [
  ['Data and purposes', 'Account identifiers, names, email addresses, phone numbers and authentication records are used for login, account administration and support. Merchant store details, addresses, categories, coordinates and uploaded images are used for onboarding, discovery and visits. Purchase amounts, reward balances, transaction references and activity records support rewards, reconciliation and dispute checks. Employee sessions, GPS visit details and notes support field operations and supervision.'],
  ['Location, photographs and notifications', 'Browser/device permissions control location and notification access. Customer location supports nearby-store discovery. Field location behaviour is described in the employee terms. Device push tokens and notification preferences support operational alerts where configured. Upload only photographs you are authorised to provide and avoid unrelated people or sensitive documents. Declining a permission may make the corresponding feature unavailable.'],
  ['Service providers and access', 'The code integrates Supabase for database/authentication, Firebase for push messaging, Google Maps for map features, and email/WhatsApp delivery services. Providers may process relevant data under their own terms and infrastructure arrangements, including outside India. Authorised staff and merchants receive the information needed for their roles and transactions. Data may also be disclosed when required by law. Provider contracts, hosting locations and the full disclosure inventory need operational verification before this draft is adopted.'],
  ['Storage and security', 'The service uses browser storage for session access and preferences, and backend records for accounts and activity. Protect your device and sign out on shared devices. No system can guarantee absolute security. Retain data only for a documented operational or legal purpose; detailed retention periods and deletion automation must be verified before publication. A 90-day GPS deletion schedule is not promised by this draft because its operation has not been verified.'],
  ['Requests and complaints', 'Contact info@affiliateinnovations.co.in or +91 9025547577 to request access, correction, deletion, withdrawal of optional permissions or to raise a privacy complaint. Requests will be assessed subject to applicable law, identity verification and any legitimate retention obligations. Do not email passwords or identity documents unless an approved secure process is provided. This draft does not claim that a dedicated privacy officer or automated rights workflow has been appointed.'],
  ['Children and review', 'Age requirements, guardian consent where applicable, retention schedules and provider arrangements must be reviewed before this policy is adopted. This draft does not establish that the service is suitable for independent use by children.'],
];
export function Legal() {
  const [params, setParams] = useSearchParams();
  const selection = params.get('type');
  const type = ['customer', 'merchant', 'field', 'privacy'].includes(selection || '') ? selection! : window.location.pathname === '/privacy' ? 'privacy' : 'customer';
  const content = type === 'privacy' ? privacy : [...common, ...(type === 'merchant' ? merchant : type === 'field' ? field : customer)];
  return <main className="ae-legal"><header><Link to="/customer/login"><img src="/logo.png" alt="AE" /></Link><h1>Terms &amp; Privacy</h1><p>Affiliate Innovations · Chittur, Palakkad, Kerala – 678101</p></header><aside role="note">Draft v1 · 3 October 2026 · For business and legal review, not a compliance certification. Publishing this page does not record acceptance or obtain consent.</aside><nav aria-label="Legal documents">{[['customer', 'Customer Terms'], ['merchant', 'Merchant Terms'], ['field', 'Employee / Field Manager Terms'], ['privacy', 'Privacy Policy']].map(([value, label]) => <button key={value} aria-pressed={type === value} onClick={() => setParams({ type: value })}>{label}</button>)}</nav><article>{content.map(([title, body]) => <section key={title}><h2>{title}</h2><p>{body}</p></section>)}</article><footer><h2>Contact Affiliate Innovations</h2><a href="mailto:info@affiliateinnovations.co.in">info@affiliateinnovations.co.in</a><br /><a href="tel:+919025547577">+91 9025547577</a><p>Chittur, Palakkad, Kerala, India – 678101. Full registered street address to be confirmed.</p><p>Review reference: <a href="https://www.meity.gov.in/documents/act-and-policies/digital-personal-data-protection-rules-2025-gDOxUjMtQWa?pageTitle=Digital-Personal-Data-Protection-Rules-2025-2" target="_blank" rel="noopener noreferrer">MeitY data-protection rules</a>. Obtain advice on applicable provisions and commencement before adoption.</p></footer></main>;
}
