import { formatDateTime } from '../utils';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { AdminForceCloseVisit } from './AdminForceCloseVisit';
import './admin-manager-overview.css';

const time = (date?: string) => date ? formatDateTime(date) : '—';
function MapLink({ lat, lng }: { lat?: number; lng?: number }) {
  return lat != null && lng != null && Number.isFinite(Number(lat)) && Number.isFinite(Number(lng)) ? <a className="button secondary" target="_blank" rel="noopener noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${Number(lat)},${Number(lng)}`}>View location on map</a> : <span>Location unavailable</span>;
}
export function AdminManagerOverview({ data }: { data: Record<string, any> }) {
  const [tab, setTab] = useState('Visits'); const [status, setStatus] = useState('All'); const [day, setDay] = useState('');
  const visits = data.visits || []; const updates = data.updates || [];
  const filtered = visits.filter((visit: any) => status === 'All' || visit.challenge_status === status);
  return <div className="am-overview"><Link to="/field-managers">← Back to Field Managers</Link><header><h1>{data.profile.full_name || 'Field Manager'}</h1><p>{data.profile.email} · {data.profile.phone || 'Phone not provided'}</p></header><p>Latest 200 records per category. Summary counts below refer to loaded records, except the all-time onboarding total.</p><div className="am-stats">{[['Merchants onboarded (all time)',data.onboardedTotal ?? 'Unavailable'],['Active visits',visits.filter((v:any)=>v.status==='active').length],['Pending challenges',visits.filter((v:any)=>v.challenge_status==='Pending').length],['Escalated challenges',visits.filter((v:any)=>v.challenge_status==='Escalated to admin team').length],['Follow-ups',visits.filter((v:any)=>v.challenge_status==='Follow-up required').length],['Attendance days loaded',data.attendance.length]].map(([label,value])=><article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div><nav className="attendance-actions" aria-label="Manager records">{['Visits','Attendance','Onboarding & Updates','Activity','Work Requests'].map(item=><button key={item} className={`button ${tab===item?'primary':'secondary'}`} aria-pressed={tab===item} onClick={()=>setTab(item)}>{item}</button>)}</nav>
  {tab==='Visits' && <><AdminForceCloseVisit visits={visits} /><label>Challenge status<select value={status} onChange={e=>setStatus(e.target.value)}>{['All','Pending','Solved','Escalated to admin team','Follow-up required'].map(item=><option key={item}>{item}</option>)}</select></label>{!filtered.length && <p>No matching visits.</p>}{filtered.map((v:any)=><article className="panel" key={v.id}><h2>{v.merchants?.name || 'Merchant'}</h2><p>{v.admin_closed_at?'Closed by Admin':v.status==='active'?'In progress':'Completed'} · Challenge: {v.challenge_status || 'Not recorded'}</p><dl>{[['Reason',v.reason],['Description',v.notes],['Problems',v.problems],['Merchant feedback',v.feedback],['Outcome',v.outcome],['Follow-up date',v.follow_up_date],['Check-in',time(v.check_in_at)],['Closed',time(v.check_out_at)],['Admin close reason',v.admin_close_reason],['Closing Admin ID',v.admin_closed_by]].filter(([,value])=>value).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><MapLink lat={v.check_in_latitude} lng={v.check_in_longitude} />{(v.photos?.length || v.report_image) ? <details><summary>View reference photos</summary><div className="am-photos">{[...(v.photos || []),v.report_image].filter(Boolean).map((photo:string,index:number)=><img key={index} src={photo} alt={`Visit reference ${index+1}`} loading="lazy" />)}</div></details>:null}</article>)}</>}
  {tab==='Attendance' && <><h2>Daily attendance</h2><label>Filter date<input type="date" value={day} onChange={e=>setDay(e.target.value)} /></label>{!data.attendanceAvailable && <p role="alert">Attendance data unavailable. Check the attendance migration.</p>}{data.attendance.filter((a:any)=>!day || a.work_date===day).map((a:any)=><article className="panel" key={a.id}><h3>{a.work_date}</h3><p>{a.ended_at?'Day completed':'Day in progress'}</p><p>Started: {time(a.started_at)}</p><p>Ended: {time(a.ended_at)}</p><p>GPS accuracy: {a.accuracy_m == null?'Not recorded':`±${Math.ceil(a.accuracy_m)} m`}</p><MapLink lat={a.latitude} lng={a.longitude} />{a.selfie && <details><summary>View attendance reference photo</summary><img className="am-selfie" src={a.selfie} alt="Attendance reference selfie" loading="lazy" /></details>}</article>)}{data.attendanceAvailable && !data.attendance.some((a:any)=>!day || a.work_date===day) && <p>No attendance records for this selection.</p>}</>}
  {tab==='Onboarding & Updates' && <><h2>Merchant onboarding and submitted updates</h2>{updates.map((u:any)=><article className="panel" key={u.id}><h3>{u.payload?.merchant_name || u.payload?.name || 'Merchant update'}</h3><p>{u.payload?.action==='onboard_merchant'?'Onboarded merchant':'Submitted update'} · {u.status} · {time(u.created_at)}</p><Link to={`/merchants/${u.merchant_id}`}>Open merchant</Link><dl>{Object.entries(u.payload || {}).filter(([key])=>!['images','image_url'].includes(key)).map(([key,value])=><div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{typeof value==='object'?JSON.stringify(value):String(value ?? '—')}</dd></div>)}</dl></article>)}{!updates.length && <p>No records.</p>}</>}
  {tab==='Activity' && <><h2>Login / logout</h2>{(data.sessions || []).map((s:any)=><article className="panel" key={s.id}><p>Login: {time(s.login_at)}</p><p>Logout: {time(s.logout_at)}</p></article>)}<h2>Merchant profiles viewed</h2>{!data.activityAvailable && <p role="alert">Profile-view tracking is unavailable.</p>}{(data.activity || []).map((a:any)=><article className="panel" key={a.id}><strong>{a.merchants?.name || 'Merchant'}</strong><p>{a.action} · {time(a.created_at)}</p></article>)}</>}
  {tab==='Work Requests' && <>{!data.workRequestsAvailable && <p role="alert">Work requests unavailable.</p>}{(data.workRequests || []).map((r:any)=><article className="panel" key={r.id}><h3>{r.kind==='leave'?'Leave':'Non-field work'}</h3><p>{r.status} · {r.reason}</p><p>{time(r.starts_at)} – {time(r.ends_at)}</p></article>)}{data.workRequestsAvailable && !data.workRequests.length && <p>No work requests.</p>}</>}
  </div>;
}
