import { uiText } from '../uiText';
import { formatDateTime } from '../utils';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { AdminForceCloseVisit } from './AdminForceCloseVisit';
import './admin-manager-overview.css';

const time = (date?: string) => date ? formatDateTime(date) : '—';
function MapLink({ lat, lng }: { lat?: number; lng?: number }) {
  return lat != null && lng != null && Number.isFinite(Number(lat)) && Number.isFinite(Number(lng)) ? <a className="button secondary" target="_blank" rel="noopener noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${Number(lat)},${Number(lng)}`}>{uiText("View location on map")}</a> : <span>{uiText("Location unavailable")}</span>;
}
export function AdminManagerOverview({ data }: { data: Record<string, any> }) {
  const [tab, setTab] = useState('Visits'); const [status, setStatus] = useState('All'); const [day, setDay] = useState('');
  const visits = data.visits || []; const updates = data.updates || [];
  const filtered = visits.filter((visit: any) => status === 'All' || visit.challenge_status === status);
  return <div className="am-overview"><Link to="/field-managers">{uiText("← Back to Field Managers")}</Link><header><h1>{data.profile.full_name || 'Field Manager'}</h1><p>{data.profile.email} · {data.profile.phone || 'Phone not provided'}</p></header><p>{uiText("Latest 200 records per category. Summary counts below refer to loaded records, except the all-time onboarding total.")}</p><div className="am-stats">{[['Merchants onboarded (all time)',data.onboardedTotal ?? 'Unavailable'],['Active visits',visits.filter((v:any)=>v.status==='active').length],['Pending challenges',visits.filter((v:any)=>v.challenge_status==='Pending').length],['Escalated challenges',visits.filter((v:any)=>v.challenge_status==='Escalated to admin team').length],['Follow-ups',visits.filter((v:any)=>v.challenge_status==='Follow-up required').length],['Attendance days loaded',data.attendance.length]].map(([label,value])=><article key={label}><strong>{value}</strong><span>{uiText(label)}</span></article>)}</div><nav className="attendance-actions" aria-label={uiText("Manager records")}>{['Visits','Attendance','Onboarding & Updates','Activity','Work Requests'].map(item=><button key={item} className={`button ${tab===item?'primary':'secondary'}`} aria-pressed={tab===item} onClick={()=>setTab(item)}>{item}</button>)}</nav>
  {tab==='Visits' && <><AdminForceCloseVisit visits={visits} /><label>{uiText("Challenge status")}<select value={status} onChange={e=>setStatus(e.target.value)}>{['All','Pending','Solved','Escalated to admin team','Follow-up required'].map(item=><option key={item}>{item}</option>)}</select></label>{!filtered.length && <p>{uiText("No matching visits.")}</p>}{filtered.map((v:any)=><article className="panel" key={v.id}><h2>{v.merchants?.name || 'Merchant'}</h2><p>{v.admin_closed_at?uiText("Closed by Admin"):v.status==='active'?uiText("In progress"):uiText("Completed")}{uiText(" · Challenge: ")}{v.challenge_status || 'Not recorded'}</p><dl>{[['Reason',v.reason],['Description',v.notes],['Problems',v.problems],['Merchant feedback',v.feedback],['Outcome',v.outcome],['Follow-up date',v.follow_up_date],['Check-in',time(v.check_in_at)],['Closed',time(v.check_out_at)],['Admin close reason',v.admin_close_reason],['Closing Admin ID',v.admin_closed_by]].filter(([,value])=>value).map(([label,value])=><div key={label}><dt>{uiText(label)}</dt><dd>{value}</dd></div>)}</dl><MapLink lat={v.check_in_latitude} lng={v.check_in_longitude} />{(v.photos?.length || v.report_image) ? <details><summary>{uiText("View reference photos")}</summary><div className="am-photos">{[...(v.photos || []),v.report_image].filter(Boolean).map((photo:string,index:number)=><img key={index} src={photo} alt={`Visit reference ${index+1}`} loading="lazy" />)}</div></details>:null}</article>)}</>}
  {tab==='Attendance' && <><h2>{uiText("Daily attendance")}</h2><label>{uiText("Filter date")}<input type="date" value={day} onChange={e=>setDay(e.target.value)} /></label>{!data.attendanceAvailable && <p role="alert">{uiText("Attendance data unavailable. Check the attendance migration.")}</p>}{data.attendance.filter((a:any)=>!day || a.work_date===day).map((a:any)=><article className="panel" key={a.id}><h3>{a.work_date}</h3><p>{a.ended_at?uiText("Day completed"):uiText("Day in progress")}</p><p>{uiText("Started: ")}{time(a.started_at)}</p><p>{uiText("Ended: ")}{time(a.ended_at)}</p><p>{uiText("GPS accuracy: ")}{a.accuracy_m == null?uiText("Not recorded"):`±${Math.ceil(a.accuracy_m)} m`}</p><MapLink lat={a.latitude} lng={a.longitude} />{a.selfie && <details><summary>{uiText("View attendance reference photo")}</summary><img className="am-selfie" src={a.selfie} alt={uiText("Attendance reference selfie")} loading="lazy" /></details>}</article>)}{data.attendanceAvailable && !data.attendance.some((a:any)=>!day || a.work_date===day) && <p>{uiText("No attendance records for this selection.")}</p>}</>}
  {tab==='Onboarding & Updates' && <><h2>{uiText("Merchant onboarding and submitted updates")}</h2>{updates.map((u:any)=><article className="panel" key={u.id}><h3>{u.payload?.merchant_name || u.payload?.name || 'Merchant update'}</h3><p>{u.payload?.action==='onboard_merchant'?uiText("Onboarded merchant"):uiText("Submitted update")} · {u.status} · {time(u.created_at)}</p><Link to={`/merchants/${u.merchant_id}`}>{uiText("Open merchant")}</Link><dl>{Object.entries(u.payload || {}).filter(([key])=>!['images','image_url'].includes(key)).map(([key,value])=><div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{typeof value==='object'?JSON.stringify(value):String(value ?? '—')}</dd></div>)}</dl></article>)}{!updates.length && <p>{uiText("No records.")}</p>}</>}
  {tab==='Activity' && <><h2>{uiText("Login / logout")}</h2>{(data.sessions || []).map((s:any)=><article className="panel" key={s.id}><p>{uiText("Login: ")}{time(s.login_at)}</p><p>{uiText("Logout: ")}{time(s.logout_at)}</p></article>)}<h2>{uiText("Merchant profiles viewed")}</h2>{!data.activityAvailable && <p role="alert">{uiText("Profile-view tracking is unavailable.")}</p>}{(data.activity || []).map((a:any)=><article className="panel" key={a.id}><strong>{a.merchants?.name || 'Merchant'}</strong><p>{a.action} · {time(a.created_at)}</p></article>)}</>}
  {tab==='Work Requests' && <>{!data.workRequestsAvailable && <p role="alert">{uiText("Work requests unavailable.")}</p>}{(data.workRequests || []).map((r:any)=><article className="panel" key={r.id}><h3>{r.kind==='leave'?uiText("Leave"):uiText("Non-field work")}</h3><p>{r.status} · {r.reason}</p><p>{time(r.starts_at)} – {time(r.ends_at)}</p></article>)}{data.workRequestsAvailable && !data.workRequests.length && <p>{uiText("No work requests.")}</p>}</>}
  </div>;
}
