import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { apiFetch } from '../api';

type Visit = { id: string; status: string; check_in_at: string; merchants?: { name?: string }; admin_closed_by?: string; admin_closed_at?: string; admin_close_reason?: string };
export function AdminForceCloseVisit({ visits }: { visits: Visit[] }) {
  const [selected, setSelected] = useState<Visit | null>(null); const [reason, setReason] = useState(''); const client = useQueryClient();
  const close = useMutation({ mutationFn: () => apiFetch(`/api/admin/field-visits/${encodeURIComponent(selected!.id)}/force-close`, { method: 'POST', body: JSON.stringify({ reason: reason.trim() }) }), onSuccess: () => { setSelected(null); setReason(''); void client.invalidateQueries({ queryKey: ['read-profile'] }); void client.invalidateQueries({ queryKey: ['field-visits'] }); } });
  const active = visits.filter(visit => visit.status === 'active');
  return <section className="panel"><h2>Active visits — Admin override</h2><p>Use only when a manager cannot return to the shop to check out. No checkout GPS will be recorded.</p>{!active.length && <p>No active visits.</p>}{active.map(visit => <div key={visit.id} style={{ padding: 14 }}><strong>{visit.merchants?.name || 'Merchant'}</strong><p>Started: {new Date(visit.check_in_at).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}</p><button className="button secondary" onClick={() => { setSelected(visit); setReason(''); close.reset(); }}>Force Close Visit</button></div>)}{selected && <div className="modal-backdrop"><form className="modal" role="dialog" aria-modal="true" aria-label="Force close visit" onSubmit={event => { event.preventDefault(); close.mutate(); }}><h2>Force Close Visit</h2><p>{selected.merchants?.name || 'Merchant'} — this unlocks the manager’s next check-in and records you as the closing Admin.</p><label>Reason (mandatory)<textarea required minLength={5} maxLength={2000} rows={4} value={reason} onChange={event => setReason(event.target.value)} /></label>{close.isError && <p role="alert">{close.error.message}</p>}<div className="attendance-actions"><button className="button secondary" type="button" disabled={close.isPending} onClick={() => setSelected(null)}>Cancel</button><button className="button primary" disabled={close.isPending || reason.trim().length < 5}>{close.isPending ? 'Closing…' : 'Confirm Force Close'}</button></div></form></div>}</section>;
}
