import { useState } from 'react';
import { BookOpen, ChevronRight, FileText, HelpCircle, MapPin, Search, ShieldCheck } from 'lucide-react';
import '../field-policy.css';

const guidelines = [
  { id: 'onboarding', title: 'Onboarding Rules', section: 'Overview', icon: FileText, summary: 'Create merchant accounts and verify details before submitting.', details: ['Complete Business Details, Location, Image and Review in order.', 'Confirm the store name, phone, email and category with the merchant.', 'Select the exact store location using the map or current location, then verify it before submission.', 'Review all information before Add Merchant. Share generated credentials only with the intended merchant.', 'A storefront photo is optional. Upload JPG or PNG files no larger than 5 MB.'] },
  { id: 'kyc', title: 'KYC & Compliance', section: 'KYC & Compliance', icon: ShieldCheck, summary: 'Company verification requirements await Admin confirmation.', details: ['The current onboarding form does not collect identity documents or implement KYC verification.', 'Ask Admin which business documents and verification process are required before requesting documents.', 'Do not collect identity documents through personal messaging or an unapproved storage location.', 'Official KYC requirements have not been supplied. This page is not a legal compliance policy.'] },
  { id: 'visits', title: 'Merchant Visit Guidelines', section: 'Visit Guidelines', icon: MapPin, summary: 'Use accurate GPS check-ins and clear visit notes.', details: ['Use a location-enabled browser/device and allow location when requested.', 'Check-in is validated by the server within 150 metres of the saved merchant coordinates.', 'Poor GPS or incorrect merchant coordinates can prevent check-in. Verify the location rather than submitting a false visit.', 'Record relevant visit outcomes in notes. Notes are saved when you check out.', 'Check out when the visit finishes. Refreshing the page can recover an active visit.', 'Visit planning and photo attachments are not currently supported.'] },
  { id: 'conduct', title: 'Code of Conduct', section: 'Overview', icon: BookOpen, summary: 'Suggested working practices—not an approved company policy.', details: ['Keep merchant information accurate and communicate respectfully.', 'Do not share passwords, account information or merchant details with unrelated people.', 'Do not claim a visit took place if it did not.', 'These are suggested practices. Admin must approve the official company code of conduct.'] },
  { id: 'support', title: 'Support & Escalation', section: 'Overview', icon: HelpCircle, summary: 'Report errors with useful details and no sensitive credentials.', details: ['For an error, record the screen, merchant ID, time and exact error message.', 'Contact your Admin through your existing approved channel.', 'Do not include passwords or tokens in screenshots.', 'Support contacts and an escalation matrix have not been configured. Ask Admin for those details.'] },
  { id: 'faq', title: 'Frequently Asked Questions', section: 'FAQ', icon: HelpCircle, summary: 'Answers about onboarding, maps and visits.', details: ['Do I need an APK? No. The Field Manager module works in a web browser.', 'Why does the map not load? A configured Google Maps API key, permitted website domain and network access are required.', 'Why can I not check in? Check GPS permission, merchant coordinates and the 150-metre radius.', 'Can I skip the photo? Yes, the image step is optional.', 'Are merchant updates automatically approved? Submitted merchant updates require Admin review.', 'Can I assign merchants to managers here? No, manager assignment is not implemented yet.'] },
];

export function FieldPolicy() {
  const [tab, setTab] = useState('Overview');
  const [search, setSearch] = useState('');
  const [expanded, setExpanded] = useState<string | null>(null);
  const visible = guidelines.filter(g => (tab === 'Overview' || g.section === tab) && `${g.title} ${g.summary} ${g.details.join(' ')}`.toLowerCase().includes(search.toLowerCase()));
  return <section className="field-policy">
    <header><div><h1>Policy &amp; Guidelines</h1><p>Important information and working guidance for field staff</p></div><label className="fp-search"><Search size={17} /><input aria-label="Search guidelines" placeholder="Search in policy…" value={search} onChange={e => setSearch(e.target.value)} /></label></header>
    <nav className="fp-tabs" aria-label="Guideline categories">{['Overview', 'KYC & Compliance', 'Visit Guidelines', 'FAQ'].map(item => <button key={item} aria-pressed={tab === item} onClick={() => { setTab(item); setExpanded(null); }}>{item}</button>)}</nav>
    <div className="fp-banner"><span><FileText size={30} /></span><div><h2>Field Operations Guide</h2><p>Use these instructions for merchant onboarding and visits. Official company policies require Admin approval.</p></div><ShieldCheck size={44} /></div>
    <p className="fp-notice">Operational guidance reflects the current app. KYC rules, support contacts and the company code of conduct are not yet approved or configured.</p>
    <div className="fp-cards">{visible.map(g => <article key={g.id}><span className={`fp-icon ${g.id}`}><g.icon size={24} /></span><h2>{g.title}</h2><p>{g.summary}</p><button aria-expanded={expanded === g.id} aria-controls={`guide-${g.id}`} onClick={() => setExpanded(expanded === g.id ? null : g.id)}>{expanded === g.id ? 'Hide Details' : g.section === 'FAQ' ? 'View FAQs' : 'View Details'}<ChevronRight size={15} /></button>{expanded === g.id && <ul id={`guide-${g.id}`}>{g.details.map(detail => <li key={detail}>{detail}</li>)}</ul>}</article>)}</div>
    {!visible.length && <p className="fp-empty">No guidelines match your search. Try another keyword.</p>}
  </section>;
}
