import { uiText } from '../uiText';
import { maskedPhone } from '../maskedPhone';
import { ArrowLeft, UserRound, Crown, Gift, Percent, Wallet } from 'lucide-react';
import type { Customer } from '../types';
import { formatPoints } from '../utils';
import './scanned-checkout.css';
import { flatDiscountOptions } from '../flatDiscount';

export function ScannedCheckout({customer,combined,setCombined,amount,setAmount,rate,setRate,rates,discountType,setDiscountType,discountValue,setDiscountValue,points,notes,setNotes,busy,paymentLabel,onSubmit,onBack,paymentLocked}: {
  customer:Customer; combined:boolean;setCombined:(value:boolean)=>void;amount:string;setAmount:(value:string)=>void;rate:number;setRate:(value:number)=>void;rates:number[];discountType:'flat'|'percentage';setDiscountType:(value:'flat'|'percentage')=>void;discountValue:string;setDiscountValue:(value:string)=>void;points:number;notes:string;setNotes:(value:string)=>void;busy:boolean;paymentLabel?:string;onSubmit:()=>void;onBack:()=>void;paymentLocked:boolean;
}) {
  const purchase = Number(amount || 0);
  const value = Number(discountValue);
  const discount = combined ? Math.round(Math.min(purchase,Math.max(0,discountType === 'flat' ? value : purchase*value/100))*100)/100 : 0;
  const invalid = !Number.isFinite(purchase) || purchase < (combined?100:1) || (combined && (!discountValue.trim() || !Number.isFinite(value) || value < 0 || customer.rewardPoints < 100 || (discountType === 'flat' && !flatDiscountOptions(purchase).includes(value))));
  return <section className="scanned-checkout">
    <header className="scanned-brand"><button type="button" aria-label={uiText("Scan another customer")} onClick={onBack} disabled={busy}><ArrowLeft size={23}/></button><img src="/logo.png" alt={uiText("AE")}/><span>{uiText("Affiliate AE")}</span></header>
    <div className="scanned-customer"><div className="scanned-identity"><div className="scanned-avatar"><UserRound size={29}/></div><div><strong>{customer.name}</strong><p>{maskedPhone(customer.phone)}</p><p>{customer.id}</p></div></div><div className="scanned-balance"><Crown size={21}/><strong>{formatPoints(customer.rewardPoints)}</strong><span>{uiText("points")}</span></div></div>
    <div className="scanned-toggle" role="group" aria-label={uiText("Transaction type")}><button type="button" aria-pressed={combined} className={combined?'selected':''} disabled={busy || paymentLocked} onClick={()=>setCombined(true)}>{uiText("Redeem + Issue")}</button><button type="button" aria-pressed={!combined} className={!combined?'selected':''} disabled={busy || paymentLocked} onClick={()=>setCombined(false)}>{uiText("Issue Only")}</button></div>
    <div className="scanned-form"><div className="scanned-purchase"><label>{uiText("Purchase amount (₹)")}<input type="number" min={combined ? 100 : 1} step="0.01" value={amount} disabled={paymentLocked || busy} onChange={e=>setAmount(e.target.value)} placeholder="1,000"/></label><label>{uiText("Points per INR 100")}<select value={rate} disabled={paymentLocked || busy} onChange={e=>setRate(Number(e.target.value))}>{rates.map(n=><option key={n} value={n}>{n}{uiText(" pts")}</option>)}</select></label></div>
    {combined ? <><label>{uiText("Points to redeem (fixed)")}<input value="100" readOnly aria-readonly="true"/></label><label>{uiText("Discount type")}<select value={discountType} disabled={paymentLocked || busy} onChange={e=>setDiscountType(e.target.value as 'flat'|'percentage')}><option value="percentage">{uiText("Percentage (%)")}</option><option value="flat">{uiText("Flat (₹)")}</option></select></label><label>{discountType==='flat'?uiText("Discount amount (₹)"):uiText("Discount percentage (%)")}{discountType === 'flat' ? <select value={discountValue} disabled={paymentLocked || busy || purchase < 100} onChange={e=>setDiscountValue(e.target.value)}>{purchase < 100 && <option value="">{uiText("Enter purchase amount first")}</option>}{flatDiscountOptions(purchase).map(value=><option key={value} value={value}>{uiText("Flat ₹")}{value}</option>)}</select> : <input type="number" min="0" step="0.01" value={discountValue} disabled={paymentLocked || busy} onChange={e=>setDiscountValue(e.target.value)}/>}</label><div className="scanned-preview-grid"><div className="scanned-discount"><Percent/><section><small>{uiText("Discount value")}</small><strong>₹{discount.toFixed(2)}</strong></section></div><div><Gift/><section><small>{uiText("Points to be issued")}</small><strong>{formatPoints(points)}{uiText(" points")}</strong><em>{uiText("From purchase amount")}</em></section></div><div><Wallet/><section><small>{uiText("Net payable")}</small><strong>₹{Math.max(0,purchase-discount).toFixed(2)}</strong></section></div><div><Crown/><section><small>{uiText("New balance after txn")}</small><strong>{formatPoints(customer.rewardPoints-100+points)}{uiText(" points")}</strong><em>{formatPoints(customer.rewardPoints)} − 100 + {points}</em></section></div></div>{customer.rewardPoints<100?<p className="scanned-error" role="alert">{uiText("This customer needs 100 points at this store to redeem. Choose Issue Only to continue.")}</p>:null}</> : <><div className="scanned-earned"><Gift size={31}/><div><span>{uiText("Points to be added")}</span><strong>{formatPoints(points)}{uiText(" points")}</strong></div></div><label className="scanned-notes">{uiText("Notes (optional)")}<textarea value={notes} disabled={busy || paymentLocked} onChange={e=>setNotes(e.target.value)} placeholder={uiText("E.g., Purchase at store, special offer etc.")} maxLength={160}/></label></>}
    </div><p className="scanned-cap">{uiText("Maximum 100 points issued per purchase.")}</p><button type="button" className="scanned-submit" disabled={invalid || busy} onClick={onSubmit}>{busy?uiText("Processing…"):paymentLabel || (combined?uiText("Calculate, Redeem & Issue"):uiText("Issue Points"))}</button>
  </section>;
}
